version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - UID=1000
      - VIRTUAL_HOST=localhost
    volumes:
      - ./:/app
    ports:
      - 8080:8080